### ISSUE TITLE
Verse Exkurs Bugs

### ISSUE THREAD

**Issue by Lucas-Gruber** [Thomas-Blakeney/ArisCorp-Homepage#3]
Navi. Pfeil: Scroll Up

Exkurs Fehler:
Deckblatt: Technischer Guide... unter Planung einfügen.

Banu:
Sprache Font fehlt.
Kelch Bild einfügen.
Struktur Fixen.
Martkplatz Bild einfügen.

**Comment by Thomas-Blakeney** [comment]
Fixed.

**Comment by Lucas-Gruber** [comment]
Fixed.
